max_results = 10

file_path = "../_tabs/arxiv.md"

[[topics]]
name = "小目标"
filters = ["small object detect", "sod", "tiny object detect", "tod"]

[[topics]]
name = "注意力机制"
filters = ["Attention Mechanism"]

[[topics]]
name = "背景差分"
filters = ["Background Subtraction"]
